#80
meJubair/SWTP2 pull request #20
Opened 2024-04-15 02:07 UTC by maheshbhandari433

I've been working on creating an EditorViewSingle component, which involves managing various types of content (text, background, image, video, and embed) within a door. Here's a breakdown of the structure and functionality I've implemented so far, spanning across two components:

### `EditorViewSingle.tsx:`

1. Created a component named `DoorContent`.
2. Utilized Material-UI components such as `Paper,` `Typography,` `Button`, `TextField`, `Grid`, and `Box`.
3. Defined an enum `ContentType` to represent different types of content.
4. Defined interface `DoorContentProps.`
5. Implemented state management using React hooks:
6. `useState `for managing `activeType`, `modalContent,` `doorData`, `textConfig`, and `currentInputLabel`.
7. Implemented functions to handle changes in text configuration and content selection.
8. Utilized a function to generate text styles based on the current input label.
9. Rendered UI elements based on the active content type selected.

### `TextConfig.tsx:`

1. Created a separate component for configuring text properties.
2. Utilized Material-UI components like `TextField`, `Slider,` `Select,` and `MenuItem`.
3. Defined interface `TextConfigType` representing the properties of text configuration.
4. Implemented a function component `TextConfig` that accepts props for `onChange` handler and initial values.
5. Rendered UI elements for configuring text properties such as title, subtitle, description, font size, font weight, font family, background color, and text color.

2024-04-15 07:54 UTC, G-Uzoh commented on frontend/src/routes/EditorViewSingle.tsx
What's the purpose of the Grid on lines 124 and 125? You can delete them if they are not useful.

2024-04-15 08:08 UTC, G-Uzoh requested changes
Nice job, Mahesh. This looks really good. However, some improvements can be made:

1. Please see the comment provided on the EditorViewSingle.tsx route.
2. Lint the code using Prettier to make the code more readable.
3. Refer to the ticket on Trello for more details.

2024-04-18 06:39 UTC, JerryUusis approved these changes
Well done Mahesh!

2024-04-18 06:40 UTC, G-Uzoh approved these changes

2024-04-18 06:40 UTC, merged