#62 Implement Calendar Content Component
meJubair/SWTP2 pull request #5
Opened 2024-04-02 22:18 UTC by maheshbhandari433

This pull request addresses Trello ticket #62, focusing on developing the user experience for editors by introducing a user-friendly interface for managing calendar events. The main idea is to create a React component called "Calendar Content" to streamline calender events and store data.

Key Features:

_Calendar Grid_: Displays a grid of dates within the specified range, simplifying date navigation for editors.

_Interactive Modals:_ Allows editors to add content (text, image, or video) to each date using intuitive modals.

_Firebase Integration_: Enables submission of all calendar data to Firebase.

**Changes made**:

Display a grid of dates within the specified range.
Implement modals for adding content to each date.
Enable submission of all calendar data to Firebase.
Conduct thorough testing to verify functionality.

2024-04-03 10:11 UTC, JerryUusis requested changes
Nice work! Please check the comments for implementing some changes for better maintainability. After reviewing the changes remember to pull the latest version of the `main` branch.

2024-04-03 10:11 UTC, JerryUusis commented on frontend/src/components/CalendarContent.tsx
> +import { addDoc, collection } from 'firebase/firestore';
We should create a separate file to handle database logic such as `firebase.ts`. But instead of handling the database logic in the front end, we should instead use some request handler like `axios` to handle requests to the REST server. This way we can keep our front end cleaner and leave the handling of the database in the backend `POST` endpoint.

2024-04-03 10:11 UTC, JerryUusis commented on frontend/src/components/CalendarContent.tsx
> +  const handleSubmitAll = async () => {
We should migrate this in to the router file once it's set up. In the meantime you can use `axios` with `json-server` to see that data gets uploaded to a server.

2024-04-03 17:46 UTC, maheshbhandari433 commented on frontend/src/components/Breadcrumb.tsx
> What is the reason that this feature/file was removed?

The component was for BreadCrumb and it contained only the structure. Nothing much so i decided to clear the unused component for better clarity of things. And we have a separate ticket for that, i will initiate the ticket and work on that feature.

2024-04-07 20:48 UTC, maheshbhandari433 commented on frontend/src/components/CalendarContent.tsx
> +import { addDoc, collection } from 'firebase/firestore';
handling firebase logic is removed from this component.

2024-04-10 07:13 UTC, closed without merging